jstorm:
  nimbus_host: 10.1.8.203
  nimbus_thrift_port: 17627
  storm_zookeeper_servers:
    - "10.1.8.198"
    - "10.1.4.185"
    - "10.1.4.186"
  storm_zookeeper_port: 2183
  storm_zookeeper_root: /udap/collect_jstorm

topology:
  worker_num: 1
  ack_num: 1
  worker_memory: 1073741824
  cpu_slotNum: 100
  jvm_options:
  name: EmitTest
  ip: 127.0.0.1

spout:
  name: EmitDpiSpout
  packagename: com.cqx.jstorm.spout
  parall: 1

bolt:
  - name: EmitDpiIBolt
    packagename: com.cqx.jstorm.bolt
    parall: 1
    groupingcode: LOCALFIRSTGROUPING
    componentId: EmitDpiSpout
    streamId:
  - name: EmitDpiErrBolt
    packagename: com.cqx.jstorm.bolt
    parall: 1
    groupingcode: LOCALFIRSTGROUPING
    componentId: EmitDpiIBolt
    streamId: err
  - name: EmitDpiKafkaBolt
    packagename: com.cqx.jstorm.bolt
    parall: 1
    groupingcode: LOCALFIRSTGROUPING
    componentId: EmitDpiIBolt
    streamId: kafka

param:
  sourDir: d:\tmp\data\dpi\dpi_s1mme\streaminput\
  backDir: d:\tmp\data\dpi\dpi_s1mme\streambackup\
  sinkDir: d:\tmp\data\dpi\dpi_s1mme\streamoutput\
  tempDir: d:\tmp\data\dpi\dpi_s1mme\streamtmp\
  errorDir: d:\tmp\data\dpi\dpi_s1mme\errdata\
  separator: |
  dateLocal: 3
  nameSeparator: _
  bolt_num:
  kafkaConfDir: "D:/Document/Workspaces/Git/TestJStorm/TestJStorm-App-Dpi/src/main/resources/producer.properties"
  schemaUrl: "http://10.1.8.203:18061/SchemaService/getSchema?t="
  kafka_username: alice
  kafka_password: alice
  typedefs:
    - name: s1mme
      keyWord: S1MME
      isDpi: false
      value: length,city,interface,xdr_id,rat,imsi,imei,msisdn,procedure_type,subprocedure_type,procedure_start_time,procedure_delay_time,procedure_end_time,procedure_status,cause,nas_cause,s1ap_cause1,s1ap_cause2,keyword,enb_ue_s1ap_id,mme_ue_s1ap_id,old_mme_group_id,old_mme_code,m_tmsi,mcc,mnc,lac,tmsi,user_ipv4,user_ipv6,machine_ip_add_type,mme_ip_add,enb_ip_add,mme_port,enb_port,tac,cell_id,other_tac,other_eci,mac,req_count,res_count,apn,eps_bearer_number,bearer_id1,bearer_type1,bearer_qci1,bearer_status1,bearer_enb_gtp_teid1,bearer_sgw_gtp_teid1,bearer_id2,bearer_type2,bearer_qci2,bearer_status2,bearer_enb_gtp_teid2,bearer_sgw_gtp_teid2,bearer_id3,bearer_type3,bearer_qci3,bearer_status3,bearer_enb_gtp_teid3,bearer_sgw_gtp_teid3,bearer_id4,bearer_type4,bearer_qci4,bearer_status4,bearer_enb_gtp_teid4,bearer_sgw_gtp_teid4,bearer_id5,bearer_type5,bearer_qci5,bearer_status5,bearer_enb_gtp_teid5,bearer_sgw_gtp_teid5,bearer_id6,bearer_type6,bearer_qci6,bearer_status6,bearer_enb_gtp_teid6,bearer_sgw_gtp_teid6,bearer_id7,bearer_type7,bearer_qci7,bearer_status7,bearer_enb_gtp_teid7,bearer_sgw_gtp_teid7,bearer_id8,bearer_type8,bearer_qci8,bearer_status8,bearer_enb_gtp_teid8,bearer_sgw_gtp_teid8,bearer_id9,bearer_type9,bearer_qci9,bearer_status9,bearer_enb_gtp_teid9,bearer_sgw_gtp_teid9,bearer_id10,bearer_type10,bearer_qci10,bearer_status10,bearer_enb_gtp_teid10,bearer_sgw_gtp_teid10,bearer_id11,bearer_type11,bearer_qci11,bearer_status11,bearer_enb_gtp_teid11,bearer_sgw_gtp_teid11,bearer_id12,bearer_type12,bearer_qci12,bearer_status12,bearer_enb_gtp_teid12,bearer_sgw_gtp_teid12,bearer_id13,bearer_type13,bearer_qci13,bearer_status13,bearer_enb_gtp_teid13,bearer_sgw_gtp_teid13,bearer_id14,bearer_type14,bearer_qci14,bearer_status14,bearer_enb_gtp_teid14,bearer_sgw_gtp_teid14,bearer_id15,bearer_type15,bearer_qci15,bearer_status15,bearer_enb_gtp_teid15,bearer_sgw_gtp_teid15,s_year,s_month,s_day,s_hour,s_minute,request_cause,old_mme_group_id_1,paging_type,keyword_2,keyword_3,keyword_4,old_mme_code_1,old_m_tmsi,bearer_1_request_cause,bearer_1_failure_cause,bearer_2_request_cause,bearer_2_failure_cause,bearer_3_request_cause,bearer_3_failure_cause,bearer_4_request_cause,bearer_4_failure_cause,bearer_5_request_cause,bearer_5_failure_cause,bearer_6_request_cause,bearer_6_failure_cause,bearer_7_request_cause,bearer_7_failure_cause,bearer_8_request_cause,bearer_8_failure_cause,bearer_9_request_cause,bearer_9_failure_cause,bearer_10_request_cause,bearer_10_failure_cause,bearer_11_request_cause,bearer_11_failure_cause,bearer_12_request_cause,bearer_12_failure_cause,bearer_13_request_cause,bearer_13_failure_cause,bearer_14_request_cause,bearer_14_failure_cause,bearer_15_request_cause,bearer_15_failure_cause,reserve_1,reserve_2,reserve_3,old_tac,old_eci
      ruleField: ,,,,,,,parserSubstrFirst-86,,,parserTimestamp-yyyyMMddHHmmss,,parserTimestamp-yyyyMMddHHmmss,,,,,,,,,,,,,,,,,,,,,,,parserConvertHex-10,parserConvertHex-10,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
      dpirequestField:
      hwField:
      sinkField:
      rtmField: city,xdr_id,imsi,imei,msisdn,procedure_type,subprocedure_type,procedure_start_time,procedure_delay_time,procedure_end_time,procedure_status,old_mme_group_id,old_mme_code,lac,tac,cell_id,other_tac,other_eci,home_code,msisdn_home_code,old_mme_group_id_1,old_mme_code_1,old_m_tmsi,old_tac,old_eci,cause,keyword,mme_ue_s1ap_id,request_cause,keyword_2,keyword_3,keyword_4
      rtmkey: msisdn
      topic: nmc_tb_lte_s1mme

classload:
  - "com.cqx.jstorm.utils.KafkaClientJAASLoader"
