jstorm:
  nimbus_host: 10.1.8.78
  nimbus_thrift_port: 17627
  storm_zookeeper_servers: 10.1.8.78
  storm_zookeeper_port: 2182
  storm_zookeeper_root: /udap/collect_jstorm

topology:
  worker_num: 1
  ack_num: 0
  worker_memory: 1024
  name: EmitTest
  ip: 10.1.8.78

spout:
  name: EmitTestSpout
  parall: 1

bolt:
  name: EmitTestBolt
  parall: 1